set_property SRC_FILE_INFO {cfile:C:/Users/Sreeram/Documents/GitHub/VLSI-DESIGN-COURSE/FPGA/FPGA.srcs/constrs_1/new/Module_Assignment.xdc rfile:../../../FPGA.srcs/constrs_1/new/Module_Assignment.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {C}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {Z}]
